const TOKEN=process.env.TELEGRAM_BOT_TOKEN;const API=`https://api.telegram.org/bot${TOKEN}`;const SITE='https://timi-portugal.vercel.app/';const RODOLFO='https://t.me/rodolfoguedes';const AFFILIATE='https://timihqs.com/#/pages/login/registerView?code=d3of54';
async function telegram(method,body){const r=await fetch(`${API}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return r.json()}
async function sendMessage(chat_id,text,keyboard){const body={chat_id,text,parse_mode:'HTML',disable_web_page_preview:true};if(keyboard)body.reply_markup={inline_keyboard:keyboard};return telegram('sendMessage',body)}
const cb=(text,data)=>({text,callback_data:data}),url=(text,link)=>({text,url:link}),homeRow=[cb('🏠 Menu principal','home')];
const home=id=>sendMessage(id,'👋 <b>Bem-vindo ao TIMI Portugal</b>\n\nAqui pode entender o projeto, as modalidades, a rotina diária, o ciclo de 365 dias, levantamentos, indicações e regras importantes.\n\nEscolha uma opção:',[[cb('🟢 Conhecer a TIMI','conhecer')],[cb('📅 Funcionamento diário','diario')],[cb('💰 Modalidades T2/T3/T4','modalidades')],[cb('🔄 Ciclo de 365 dias','ciclo')],[cb('💵 Levantamentos','levantamentos')],[cb('🚀 Como participar','participar')],[cb('🤝 Indicações','indicacoes')],[cb('🇵🇹 TIMI em Portugal','portugal')],[cb('🎥 Vídeos','videos')],[cb('❓ Regras e FAQ','faq')],[url('👤 Falar com Rodolfo',RODOLFO)]]);
const conhecer=id=>sendMessage(id,'🟢 <b>Como funciona a TIMI</b>\n\nA TIMI é um projeto ligado à mobilidade partilhada com bicicletas convencionais e elétricas.\n\nOnde o serviço está disponível, o público localiza uma bicicleta, utiliza a aplicação, lê o QR Code e paga pelo uso.\n\nO projeto também possui modalidades de participação com valores, duração e regras próprias.',[[cb('📅 Rotina diária','diario')],[cb('💰 Ver modalidades','modalidades')],[cb('🇵🇹 TIMI em Portugal','portugal')],[url('🌐 Ver no site',`${SITE}#projeto`)],homeRow]);
const diario=id=>sendMessage(id,'📅 <b>Funcionamento diário</b>\n\nNos dias elegíveis, o participante acompanha os grupos, obtém o código diário e insere-o na aplicação TIMI.\n\n🕙 <b>10:00–13:00</b>\n🌙 <b>19:00–22:00</b>\nHorário de Portugal. Basta utilizar uma das janelas.\n\nA atividade ocorre nos dias úteis elegíveis, excluindo fins de semana e feriados nacionais. Se perder as duas janelas, o valor daquele dia não é recuperado.\n\nO código funciona como mecanismo de participação e acompanhamento das informações do projeto.',[[cb('⚠️ Ausências e regras','ausencias')],[cb('❓ FAQ','faq')],[url('🌐 Ver no site',`${SITE}#como-funciona`)],homeRow]);
const modalidades=id=>sendMessage(id,'💰 <b>Modalidades T2/T3/T4</b>\n\n🟢 <b>T2</b> — 230 USDT\nValor diário: <b>5 USDT</b>\n\n🔵 <b>T3</b> — 560 USDT\nValor diário: <b>13 USDT</b>\n\n🟣 <b>T4</b> — 1.300 USDT\nValor diário: <b>30 USDT</b>\n\nA contabilização depende dos dias elegíveis, da atividade diária e das regras da modalidade. Os valores não constituem garantia de rendimento e os levantamentos estão sujeitos às taxas aplicáveis.',[[cb('📊 Comparar','comparar')],[cb('🔄 Ciclo','ciclo')],[cb('💵 Levantamentos','levantamentos')],[cb('🚀 Como participar','participar')],homeRow]);
const comparar=id=>sendMessage(id,'📊 <b>Comparação rápida</b>\n\nT2: 230 USDT → 5 USDT/dia\nT3: 560 USDT → 13 USDT/dia\nT4: 1.300 USDT → 30 USDT/dia\n\nOs valores são anteriores à taxa de levantamento e não representam retorno líquido garantido.',[[cb('💵 Levantamentos','levantamentos')],[cb('🔄 Ciclo','ciclo')],homeRow]);
const ciclo=id=>sendMessage(id,'🔄 <b>Ciclo de 365 dias</b>\n\nCada modalidade tem duração de <b>365 dias</b>.\n\n🔄 <b>Continuar</b> — renovação por 50% do valor original.\n↪️ <b>Encerrar</b> — ao concluir o ciclo, a regra prevê reembolso de 50% do valor original.\n\nExemplo T4: 1.300 USDT → 650 USDT para renovação ou 650 USDT no encerramento.\n\nNão existe um procedimento normal de cancelamento com reembolso antecipado antes do fim do ciclo. Consulte as condições atuais na aplicação.',[[cb('❓ FAQ','faq')],[url('🌐 Ver no site',`${SITE}#ciclo`)],homeRow]);
const levantamentos=id=>sendMessage(id,'💵 <b>Levantamentos</b>\n\nMínimos: T2 — <b>30 USDT</b> | T3 — <b>50 USDT</b> | T4 — <b>100 USDT</b>\n\nCada levantamento tem <b>taxa de 25%</b>. Exemplo: ao solicitar 100, o valor após essa taxa é 75, antes de eventuais custos externos.\n\nFluxo: TIMI → criptoativo → OKX → EUR → banco. O envio TIMI → OKX costuma levar cerca de 3 dias úteis, podendo variar.',[[cb('🔐 Segurança cripto','cripto')],[cb('🚀 Como participar','participar')],homeRow]);
const participar=id=>sendMessage(id,'🚀 <b>Como participar</b>\n\n<b>EUR → OKX → USDT/USDC → Polygon → TIMI → T2/T3/T4</b>\n\n1️⃣ Preparar os fundos.\n2️⃣ Converter para o criptoativo indicado.\n3️⃣ Confirmar moeda, rede e endereço na TIMI.\n4️⃣ Transferir e aguardar a confirmação.\n5️⃣ Ler as condições e selecionar a modalidade.\n\n⚠️ Utilize somente o endereço mostrado na sua própria conta TIMI e confirme todos os dados antes de enviar.',[[cb('🔐 Segurança cripto','cripto')],[url('🌐 Abrir plataforma TIMI',AFFILIATE)],[url('👤 Falar com Rodolfo',RODOLFO)],homeRow]);
const cripto=id=>sendMessage(id,'🔐 <b>Segurança em transferências</b>\n\nUSDT e USDC são criptoativos diferentes. Polygon é uma rede blockchain. A moeda, rede e endereço precisam corresponder exatamente aos dados da plataforma. Transferências podem ser irreversíveis. Nunca partilhe senha, SMS/2FA ou frase de recuperação.',[[cb('🚀 Como participar','participar')],[url('👤 Pedir ajuda',RODOLFO)],homeRow]);
const indicacoes=id=>sendMessage(id,'🤝 <b>Indicações</b>\n\n<b>Indicar outras pessoas é opcional.</b> É possível participar durante todo o ciclo sem indicar ninguém, mantendo as regras da própria modalidade e a atividade diária.\n\nExiste também um programa separado de progressão e benefícios por indicação. Critérios e benefícios devem ser consultados nas regras atuais.',[[url('🌐 Ver no site',`${SITE}#indicacao`)],[url('👤 Perguntar a Rodolfo',RODOLFO)],homeRow]);
const portugal=id=>sendMessage(id,'🇵🇹 <b>TIMI em Portugal</b>\n\nA TIMI já possui presença do projeto em Portugal. Lisboa, Portimão e Aveiro estão entre as cidades divulgadas. Porto integra a expansão comunicada e a disponibilidade deve ser confirmada.\n\nPara o público: localizar bicicleta → abrir aplicação → ler QR Code → utilizar o serviço.\n\nA operação física e as condições financeiras das modalidades são aspetos distintos; consulte as regras de cada modalidade antes de participar.',[[cb('🎥 Ver vídeos','videos')],[url('🌐 Ver no site',`${SITE}#timi-portugal`)],homeRow]);
const videos=id=>sendMessage(id,'🎥 <b>Vídeos TIMI</b>\n\nVeja entrevistas, eventos e experiências da TIMI em Portugal.',[[url('⭐ Entrevista especial','https://youtu.be/QMu3hg2w_8w')],[url('🎬 Vídeo TIMI','https://youtu.be/KXUMbNIgTqU')],[url('🎉 Evento em Lisboa','https://youtu.be/ISsFWPg50gg')],[url('🇵🇹 TIMI Portugal','https://youtu.be/UBKWfs0cdA8')],[url('🌐 Ver todos no site',`${SITE}#videos`)],homeRow]);
const ausencias=id=>sendMessage(id,'⚠️ <b>Ausências e inatividade</b>\n\nA regra de participação prevê acompanhamento regular da atividade. Ausências consecutivas podem gerar medidas na conta, incluindo redução temporária do valor diário e, em casos prolongados, bloqueio ou exclusão. Situações justificadas podem ser analisadas pelo responsável.\n\nOs valores dos dias em que o código não foi realizado não são recuperados. Consulte sempre as regras atuais da plataforma.',[[cb('📅 Funcionamento diário','diario')],[cb('❓ FAQ','faq')],homeRow]);
const faq=id=>sendMessage(id,'❓ <b>Regras e dúvidas frequentes</b>\n\nEscolha o assunto:',[[cb('⏰ Perdi o código','faq_codigo')],[cb('⚠️ Ausências / bloqueio','ausencias')],[cb('🔄 Sair antes de 365 dias','faq_saida')],[cb('💵 Taxa e mínimos','levantamentos')],[cb('🤝 Preciso indicar?','indicacoes')],[cb('💬 O que é BonChat?','faq_bonchat')],[cb('📄 Existe contrato PDF?','faq_contrato')],[cb('📈 Valores são garantidos?','faq_garantido')],[cb('🔐 Segurança','cripto')],[url('👤 Falar com Rodolfo',RODOLFO)],homeRow]);
const faqCodigo=id=>sendMessage(id,'⏰ <b>Perdi o código diário. E agora?</b>\n\nSe nenhuma das duas janelas for utilizada no dia elegível, o valor daquele dia é perdido e não pode ser recuperado.',[[cb('📅 Rotina diária','diario')],[cb('⬅️ FAQ','faq')],homeRow]);
const faqSaida=id=>sendMessage(id,'🔄 <b>Posso sair antes dos 365 dias?</b>\n\nNão existe um procedimento normal de cancelamento com reembolso antecipado. O reembolso de 50% aplica-se ao encerramento normal após a conclusão do ciclo, conforme as condições vigentes.',[[cb('🔄 Ver ciclo','ciclo')],[cb('⬅️ FAQ','faq')],homeRow]);
const faqBonchat=id=>sendMessage(id,'💬 <b>O que é BonChat?</b>\n\nBonChat não é a aplicação TIMI. É uma ferramenta externa de comunicação utilizada para grupos, códigos, formações, eventos, comunicados e acompanhamento dos participantes.',[[cb('📅 Rotina diária','diario')],[cb('⬅️ FAQ','faq')],homeRow]);
const faqContrato=id=>sendMessage(id,'📄 <b>Existe contrato individual em PDF?</b>\n\nAs regras e condições ficam disponíveis dentro da aplicação. Normalmente não é fornecido um contrato individual em PDF ou por e-mail. Leia e guarde as condições vigentes antes de participar.',[[cb('⬅️ FAQ','faq')],homeRow]);
const faqGarantido=id=>sendMessage(id,'📈 <b>Os valores são garantidos?</b>\n\nNão. Os valores das modalidades dependem das regras, dias elegíveis, atividade exigida e funcionamento da plataforma. Não devem ser tratados como promessa de rendimento garantido.',[[cb('💰 Modalidades','modalidades')],[cb('⬅️ FAQ','faq')],homeRow]);
const desconhecido=id=>sendMessage(id,'🤖 Não identifiquei essa opção. Utilize o menu abaixo ou fale diretamente com Rodolfo.',[[cb('🏠 Abrir menu','home')],[url('👤 Falar com Rodolfo',RODOLFO)]]);
export default async function handler(req,res){if(req.method!=='POST')return res.status(200).json({ok:true,service:'TIMI Portugal Telegram Bot'});if(!TOKEN)return res.status(500).json({ok:false,error:'Bot token not configured'});try{const u=req.body;if(u.message){const id=u.message.chat.id,t=u.message.text?.trim().toLowerCase()||'';await((t==='/start'||t==='/menu'||t==='menu')?home:desconhecido)(id);return res.status(200).json({ok:true})}if(u.callback_query){const q=u.callback_query,id=q.message.chat.id;await telegram('answerCallbackQuery',{callback_query_id:q.id});const a={home,conhecer,diario,modalidades,comparar,ciclo,levantamentos,participar,cripto,indicacoes,portugal,videos,ausencias,faq,faq_codigo:faqCodigo,faq_saida:faqSaida,faq_bonchat:faqBonchat,faq_contrato:faqContrato,faq_garantido:faqGarantido};await(a[q.data]||desconhecido)(id);return res.status(200).json({ok:true})}return res.status(200).json({ok:true})}catch(e){console.error(e);return res.status(200).json({ok:false})}}
