const TOKEN=process.env.TELEGRAM_BOT_TOKEN;const API=`https://api.telegram.org/bot${TOKEN}`;const SITE='https://timi-portugal.vercel.app/';const RODOLFO='https://t.me/rodolfoguedes';const AFFILIATE='https://timihqs.com/#/pages/login/registerView?code=d3of54';
async function telegram(method,body){const r=await fetch(`${API}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return r.json()}
async function sendMessage(chat_id,text,keyboard){const body={chat_id,text,parse_mode:'HTML',disable_web_page_preview:true};if(keyboard)body.reply_markup={inline_keyboard:keyboard};return telegram('sendMessage',body)}
const cb=(text,data)=>({text,callback_data:data}),url=(text,link)=>({text,url:link}),homeRow=[cb('🏠 Menu principal','home')];
const home=id=>sendMessage(id,'👋 <b>Bem-vindo ao TIMI Portugal</b>\n\nAqui pode conhecer o projeto, modalidades, rotina diária, ciclo, levantamentos e outras informações úteis.\n\nEscolha uma opção:',[[cb('🟢 Conhecer a TIMI','conhecer')],[cb('📅 Funcionamento diário','diario')],[cb('💰 Modalidades T2/T3/T4','modalidades')],[cb('🔄 Ciclo de 365 dias','ciclo')],[cb('💵 Levantamentos','levantamentos')],[cb('🚀 Como participar','participar')],[cb('🤝 Indicações','indicacoes')],[cb('🇵🇹 TIMI em Portugal','portugal')],[cb('🎥 Vídeos','videos')],[cb('❓ Regras e FAQ','faq')],[cb('ℹ️ Informações importantes','informacoes')],[url('👤 Falar com Rodolfo',RODOLFO)]]);
const conhecer=id=>sendMessage(id,'🟢 <b>Como funciona a TIMI</b>\n\nA TIMI é um projeto ligado à mobilidade partilhada com bicicletas convencionais e elétricas.\n\nOnde o serviço está disponível, o público localiza uma bicicleta, utiliza a aplicação, lê o QR Code e paga pelo uso.\n\nO projeto também possui modalidades de participação com valores, duração e regras próprias.',[[cb('📅 Rotina diária','diario')],[cb('💰 Ver modalidades','modalidades')],[cb('🇵🇹 TIMI em Portugal','portugal')],homeRow]);
const diario=id=>sendMessage(id,'📅 <b>Funcionamento diário</b>\n\nNos dias elegíveis, o participante acompanha os grupos, obtém o código diário e insere-o na aplicação TIMI.\n\n🕙 <b>10:00–13:00</b>\n🌙 <b>19:00–22:00</b>\nHorário de Portugal. Basta utilizar uma das janelas.\n\nA atividade ocorre nos dias úteis elegíveis, excluindo fins de semana e feriados nacionais. Se perder as duas janelas, o valor daquele dia não é recuperado.\n\nO código funciona como mecanismo de participação e acompanhamento das informações do projeto.',[[cb('⚠️ Ausências e regras','ausencias')],[cb('❓ FAQ','faq')],homeRow]);
const modalidades=id=>sendMessage(id,'💰 <b>Modalidades T2/T3/T4</b>\n\n🟢 <b>T2</b> — 230 USDT\nValor diário: <b>5 USDT</b>\n\n🔵 <b>T3</b> — 560 USDT\nValor diário: <b>13 USDT</b>\n\n🟣 <b>T4</b> — 1.300 USDT\nValor diário: <b>30 USDT</b>\n\nA contabilização ocorre nos dias elegíveis mediante a atividade diária prevista na modalidade.',[[cb('📊 Comparar','comparar')],[cb('🔄 Ciclo','ciclo')],[cb('💵 Levantamentos','levantamentos')],[cb('🚀 Como participar','participar')],homeRow]);
const comparar=id=>sendMessage(id,'📊 <b>Comparação rápida</b>\n\nT2: 230 USDT → 5 USDT/dia\nT3: 560 USDT → 13 USDT/dia\nT4: 1.300 USDT → 30 USDT/dia\n\nOs valores acima são anteriores à taxa de levantamento.',[[cb('💵 Levantamentos','levantamentos')],[cb('🔄 Ciclo','ciclo')],homeRow]);
const ciclo=id=>sendMessage(id,'🔄 <b>Ciclo de 365 dias</b>\n\nCada modalidade tem duração de <b>365 dias</b>.\n\n🔄 <b>Continuar</b> — renovação por 50% do valor original.\n↪️ <b>Encerrar</b> — ao concluir o ciclo, a regra prevê reembolso de 50% do valor original.\n\nExemplo T4: 1.300 USDT → 650 USDT para renovação ou 650 USDT no encerramento.\n\nNão existe um procedimento normal de cancelamento com reembolso antecipado antes do fim do ciclo.',[[cb('❓ FAQ','faq')],homeRow]);
const levantamentos=id=>sendMessage(id,'💵 <b>Levantamentos</b>\n\nMínimos: T2 — <b>30 USDT</b> | T3 — <b>50 USDT</b> | T4 — <b>100 USDT</b>\n\nCada levantamento tem <b>taxa de 25%</b>. Exemplo: ao solicitar 100, o valor após essa taxa é 75, antes de eventuais custos externos.\n\nFluxo: TIMI → criptoativo → OKX → EUR → banco. O envio TIMI → OKX costuma levar cerca de 3 dias úteis.',[[cb('🔐 Segurança cripto','cripto')],[cb('🚀 Como participar','participar')],homeRow]);
const participar=id=>sendMessage(id,'🚀 <b>Como participar</b>\n\n<b>EUR → OKX → USDT/USDC → Polygon → TIMI → T2/T3/T4</b>\n\n1️⃣ Preparar os fundos.\n2️⃣ Converter para o criptoativo indicado.\n3️⃣ Confirmar moeda, rede e endereço na TIMI.\n4️⃣ Transferir e aguardar a confirmação.\n5️⃣ Ler as condições e selecionar a modalidade.',[[cb('🔐 Segurança cripto','cripto')],[url('🌐 Abrir plataforma TIMI',AFFILIATE)],[url('👤 Falar com Rodolfo',RODOLFO)],homeRow]);
const cripto=id=>sendMessage(id,'🔐 <b>Transferências</b>\n\nUSDT e USDC são criptoativos diferentes e Polygon é uma rede blockchain. Utilize os dados mostrados na sua própria conta TIMI e confira moeda, rede e endereço antes de enviar.',[[cb('🚀 Como participar','participar')],[cb('ℹ️ Informações importantes','informacoes')],homeRow]);
const indicacoes=id=>sendMessage(id,'🤝 <b>Indicações</b>\n\n<b>Indicar outras pessoas é opcional.</b> É possível participar durante todo o ciclo sem indicar ninguém, mantendo as regras da modalidade e a atividade diária.\n\nExiste também um programa separado de progressão e benefícios por indicação.',[[url('🌐 Ver no site',`${SITE}#indicacao`)],[url('👤 Perguntar a Rodolfo',RODOLFO)],homeRow]);
const portugal=id=>sendMessage(id,'🇵🇹 <b>TIMI em Portugal</b>\n\nA TIMI já possui presença do projeto em Portugal. Lisboa, Portimão e Aveiro estão entre as cidades divulgadas. Porto integra a expansão comunicada.\n\nPara o público: localizar bicicleta → abrir aplicação → ler QR Code → utilizar o serviço.',[[cb('🎥 Ver vídeos','videos')],[url('🌐 Ver no site',`${SITE}#timi-portugal`)],homeRow]);
const videos=id=>sendMessage(id,'🎥 <b>Vídeos TIMI</b>\n\nVeja entrevistas, eventos e experiências da TIMI em Portugal.',[[url('⭐ Entrevista especial','https://youtu.be/QMu3hg2w_8w')],[url('🎬 Vídeo TIMI','https://youtu.be/KXUMbNIgTqU')],[url('🎉 Evento em Lisboa','https://youtu.be/ISsFWPg50gg')],[url('🇵🇹 TIMI Portugal','https://youtu.be/UBKWfs0cdA8')],homeRow]);
const ausencias=id=>sendMessage(id,'⚠️ <b>Ausências e inatividade</b>\n\nA participação prevê acompanhamento regular da atividade. Ausências consecutivas podem gerar medidas na conta, incluindo redução temporária do valor diário e, em casos prolongados, bloqueio ou exclusão. Situações justificadas podem ser analisadas pelo responsável.\n\nOs valores dos dias em que o código não foi realizado não são recuperados.',[[cb('📅 Funcionamento diário','diario')],[cb('❓ FAQ','faq')],homeRow]);
const faq=id=>sendMessage(id,'❓ <b>Regras e dúvidas frequentes</b>\n\nEscolha o assunto:',[[cb('⏰ Perdi o código','faq_codigo')],[cb('⚠️ Ausências / bloqueio','ausencias')],[cb('🔄 Sair antes de 365 dias','faq_saida')],[cb('💵 Taxa e mínimos','levantamentos')],[cb('🤝 Preciso indicar?','indicacoes')],[cb('💬 O que é BonChat?','faq_bonchat')],[cb('📄 Condições na aplicação','faq_contrato')],[cb('ℹ️ Informações importantes','informacoes')],[url('👤 Falar com Rodolfo',RODOLFO)],homeRow]);
const faqCodigo=id=>sendMessage(id,'⏰ <b>Perdi o código diário. E agora?</b>\n\nSe nenhuma das duas janelas for utilizada no dia elegível, o valor daquele dia é perdido e não pode ser recuperado.',[[cb('📅 Rotina diária','diario')],[cb('⬅️ FAQ','faq')],homeRow]);
const faqSaida=id=>sendMessage(id,'🔄 <b>Posso sair antes dos 365 dias?</b>\n\nNão existe um procedimento normal de cancelamento com reembolso antecipado. O reembolso de 50% aplica-se ao encerramento normal após a conclusão do ciclo.',[[cb('🔄 Ver ciclo','ciclo')],[cb('⬅️ FAQ','faq')],homeRow]);
const faqBonchat=id=>sendMessage(id,'💬 <b>O que é BonChat?</b>\n\nBonChat não é a aplicação TIMI. É uma ferramenta externa de comunicação utilizada para grupos, códigos, formações, eventos, comunicados e acompanhamento dos participantes.',[[cb('📅 Rotina diária','diario')],[cb('⬅️ FAQ','faq')],homeRow]);
const faqContrato=id=>sendMessage(id,'📄 <b>Onde consultar as condições?</b>\n\nAs regras e condições ficam disponíveis dentro da aplicação. Leia as condições vigentes antes de selecionar uma modalidade.',[[cb('⬅️ FAQ','faq')],homeRow]);
const informacoes=id=>sendMessage(id,'ℹ️ <b>Informações importantes</b>\n\nAs informações deste bot resumem o funcionamento, valores e condições do projeto TIMI. Valores diários, prazos, taxas, regras, renovação e reembolso dependem das condições vigentes da plataforma e podem ser alterados.\n\nA participação envolve criptoativos e riscos operacionais; resultados não são garantidos. Transferências de criptoativos podem ser irreversíveis. Antes de participar, consulte as regras atuais na aplicação e confirme cuidadosamente moeda, rede e endereço em qualquer transferência.',[[url('🌐 Ver site',SITE)],[url('👤 Falar com Rodolfo',RODOLFO)],homeRow]);
const desconhecido=id=>sendMessage(id,'🤖 Não identifiquei essa opção. Utilize o menu abaixo ou fale diretamente com Rodolfo.',[[cb('🏠 Abrir menu','home')],[url('👤 Falar com Rodolfo',RODOLFO)]]);
export default async function handler(req,res){if(req.method!=='POST')return res.status(200).json({ok:true,service:'TIMI Portugal Telegram Bot'});if(!TOKEN)return res.status(500).json({ok:false,error:'Bot token not configured'});try{const u=req.body;if(u.message){const id=u.message.chat.id,t=u.message.text?.trim().toLowerCase()||'';await((t==='/start'||t==='/menu'||t==='menu')?home:desconhecido)(id);return res.status(200).json({ok:true})}if(u.callback_query){const q=u.callback_query,id=q.message.chat.id;await telegram('answerCallbackQuery',{callback_query_id:q.id});const a={home,conhecer,diario,modalidades,comparar,ciclo,levantamentos,participar,cripto,indicacoes,portugal,videos,ausencias,faq,faq_codigo:faqCodigo,faq_saida:faqSaida,faq_bonchat:faqBonchat,faq_contrato:faqContrato,informacoes};await(a[q.data]||desconhecido)(id);return res.status(200).json({ok:true})}return res.status(200).json({ok:true})}catch(e){console.error(e);return res.status(200).json({ok:false})}}
